version: '3.4'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: defesa_civil
      MYSQL_PASSWORD: 12345678
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
